config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :admins
  resources :groups do 
    member do 
      get :members
      delete :delete_member
      get :add_members
      post :add_member
      post :bulk_add
    end
  end
  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
    registrations:  'overrides/registrations'
  }
  resources :notifications, except: [:update]
  resources :notification_contents, except: [:update]
  resources :devices, only: [:update]
  resources :access

  resources :user
end

app/models/notification.rb
class Notification < ApplicationRecord
  load "#{Rails.root}/lib/ios_push_notification.rb"
  belongs_to :user
  belongs_to :notification_content
  
  validates :title, presence: true
  validates :body, presence: true

  after_create :send_push_notification

  def send_push_notification
    user = self.user
    @service = IosPushNotification.new()
    user.devices.each do |device|
      @service.send_alert_notification(device.token, self.body)
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.where(user_id: current_user.id, expired: false)
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.expired = true
    @notification.save
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.where(id: params[:id], user_id: current_user.id).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:title, :body, :user_id, :expired)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(notification) do |f| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :expired %>
    <%= f.check_box :expired %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User</th>
      <th>Expired</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.title %></td>
        <td><%= notification.body %></td>
        <td><%= notification.user_id %></td>
        <td><%= notification.expired %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @notification.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @notification.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @notification.user_id %>
</p>

<p>
  <strong>Expired:</strong>
  <%= @notification.expired %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>