config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :admins
  resources :groups do 
    member do 
      get :members
      delete :delete_member
      get :add_members
      post :add_member
      post :bulk_add
    end
  end
  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
    registrations:  'overrides/registrations'
  }
  resources :notifications, except: [:update]
  resources :notification_contents, except: [:update]
  resources :devices, only: [:update]
  resources :access

  resources :user
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members, dependent: :destroy
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :check_role
  before_action :set_group, only: [:show, :edit, :update, :destroy, :members, :delete_member, :add_members, :add_member, :bulk_add]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def members
    @members = User.joins(:memberships).where("members.group_id = ?", @group.id)
  end

  def delete_member
    Member.where(user_id: params[:user_id], group_id: @group.id).first.destroy
    respond_to do |format|
      format.html { redirect_to members_group_url(@group), notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_members
    @users = User.where("users.id NOT IN (select members.user_id from members where members.group_id = ?)", params[:id])

    if params[:first_name] && params[:first_name].present?
      @users = @users.where(first_name: params[:first_name])
    end

    if params[:last_name] && params[:last_name].present?
      @users = @users.where(last_name: params[:last_name])
    end

    if params[:serie] && params[:serie].present?
      @users = @users.where('groups @> ?', '[{ "serie":' + params[:serie].to_s + ' }]' )
    end

    if params[:year] && params[:year].present?
      @users = @users.where('groups @> ?', '[{ "year":' + params[:year].to_s + ' }]' )
    end

    if params[:group_number] && params[:group_number].present?
      @users = @users.where('groups @> ?', '[{ "group_number":' + params[:group_number].to_s + ' }]' )
    end

    if params[:group] && params[:group].present?
      @users = @users.joins(:memberships).where('members.group_id = ?', params[:group])
    end

    @series = []
    @years = []
    @group_numbers = []
    User.all.find_in_batches(batch_size: 500).each do |batch|
      batch.each do |user|
        user.groups.each do |user_hash|
          @series << user_hash['serie']
          @years << user_hash['year']
          @group_numbers << user_hash['group_number']
        end
      end
    end

    @series = @series.uniq
    @years = @years.uniq
    @group_numbers = @group_numbers.uniq
  end

  def bulk_add
    @users = User.where("users.id NOT IN (select members.user_id from members where members.group_id = ?)", params[:id])

    if params[:first_name] && params[:first_name].present?
      @users = @users.where(first_name: params[:first_name])
    end

    if params[:last_name] && params[:last_name].present?
      @users = @users.where(last_name: params[:last_name])
    end

    if params[:serie] && params[:serie].present?
      @users = @users.where('groups @> ?', '[{ "serie":' + params[:serie].to_s + ' }]' )
    end

    if params[:year] && params[:year].present?
      @users = @users.where('groups @> ?', '[{ "year":' + params[:year].to_s + ' }]' )
    end

    if params[:group_number] && params[:group_number].present?
      @users = @users.where('groups @> ?', '[{ "group_number":' + params[:group_number].to_s + ' }]' )
    end

    if params[:group] && params[:group].present?
      @users = @users.joins(:memberships).where('members.group_id = ?', params[:group])
    end

   @users.find_in_batches(batch_size: 500).each do |batch|
      batch.each do |user|
        user.memberships.create(group_id: @group.id)
      end
    end

    respond_to do |format|
      format.html { redirect_to add_members_group_url(@group), notice: "All the users are now members of #{@group.name}" }
      format.json { head :no_content }
    end
  end

  def add_member
    @user = User.find(params[:user_id])
    @user.memberships.create(group_id: @group.id)
    respond_to do |format|
      format.html { redirect_to add_members_group_url(@group), notice: "#{@user.first_name} is now a member of #{@group.name}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    def check_role
      unless current_admin && (current_admin.role == 'Master' || current_admin.role == 'Admin')
        redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(group) do |f| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/add_members.html.erb
<p id="notice"><%= notice %></p>

<h1> Users </h1>


<%= form_tag(add_members_group_path, method: :get) do %>
  <div class="field">
    <%= label_tag :FirstName %>
    <%= text_field_tag :first_name, params[:first_name], placeholder: 'first_name' %>
  </div>

  <div class="field">
    <%= label_tag :LastName %>
    <%= text_field_tag :last_name, params[:last_name], placeholder: 'last_name' %>
  </div>

  <div class="field">
    <%= label_tag :serie %>
    <%= select_tag :serie, options_for_select(@series, params[:serie]), include_blank: true %>
  </div>

  <div class="field">
    <%= label_tag :year %>
    <%= select_tag :year, options_for_select(@years, params[:year]), include_blank: true %>
  </div>

  <div class="field">
    <%= label_tag :group_number %>
    <%= select_tag :group_number, options_for_select(@group_numbers, params[:group_number]), include_blank: true %>
  </div>

  <div class="field">
    <%= label_tag :group %>
    <%= select_tag :group, options_from_collection_for_select(Group.all, :id, :name, params[:group]), include_blank: true %>
  </div>

  <%= submit_tag "Search" %>
<% end %>


<%= link_to 'Add all selected users', bulk_add_group_path(@group, params.permit(:first_name, :last_name, :serie, :year, :group_number, :group)), method: :post, data: { confirm: 'Are you sure?' } %>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Series</th>
      <th>Year</th>
      <th>Group Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %> </td>
        <td><%= user.groups.map{ |el| el['serie']} %></td>
        <td><%= user.groups.map{ |el| el['year']} %></td>
        <td><%= user.groups.map{ |el| el['group_number']} %></td>
        <td><%= link_to 'Add to Group', add_member_group_path(@group, user_id: user.id), method: :post, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.description %></td>
        <td><%= link_to 'Members', members_group_path(group) %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/members.html.erb
<h1> Members </h1>

<h3> <%= @group.name %> </h3>
<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Series</th>
      <th>Year</th>
      <th>Group Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.first_name %></td>
        <td><%= member.last_name %> </td>
        <td><%= member.groups.map{ |el| el['serie']} %></td>
        <td><%= member.groups.map{ |el| el['year']} %></td>
        <td><%= member.groups.map{ |el| el['group_number']} %></td>
        <td><%= link_to 'Delete', delete_member_group_path(@group, user_id: member.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Members', add_members_group_path(@group) %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group.description %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>