config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :admins
  resources :groups do 
    member do 
      get :members
      delete :delete_member
      get :add_members
      post :add_member
      post :bulk_add
    end
  end
  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
    registrations:  'overrides/registrations'
  }
  resources :notifications, except: [:update]
  resources :notification_contents, except: [:update]
  resources :devices, only: [:update]
  resources :access

  resources :user
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if current_admin.present? %>
          <li><%= link_to "Notifications", new_notification_content_path %></li>
          <li><%= link_to "Groups", groups_path %></li>
          <% if current_admin && current_admin.role == 'Master' %>
            <li><%= link_to "Admins", access_index_path%></li>
          <% end %>
          <%= link_to "Log out", destroy_admin_session_path, method: "delete" %>
        <% else %>
          <li><%= link_to "Log in", new_admin_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotificationApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
    </div>
    <div class="container" style='margin-top: 200px'>
      <%= yield %>
    </div>
  </body>
</html>